class UserNotFoundException(Exception):
    pass

class InvalidUserException(Exception):
    pass